### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by kvz** [transloadit/transloadify#13]
`npm install -g transloadify@0.2.2`

with `steps.json` being:

```json
{
  "webp": {
    "use": ":original",
    "robot": "/image/resize",
    "result": true,
    "imagemagick_stack": "v2.0.3",
    "format": "webp"
  }
}
```

and the following command:

```bash
env \
  TRANSLOADIT_KEY=xx \
  TRANSLOADIT_SECRET=yy \
transloadify \
  --steps ./steps.json < assets/images/logo_milan_white_10.png > output.webp
```

I'm getting:

```bash
ERROR   TypeError: Cannot read property '0' of undefined
    at callback (../src/assemblies-create.js:430:25)
    at _fulfilled (/usr/local/lib/node_modules/transloadify/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/transloadify/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/transloadify/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/transloadify/node_modules/q/q.js:604:44
    at runSingle (/usr/local/lib/node_modules/transloadify/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/transloadify/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by kvz** [comment]
Hey @ifedapoolarewaju, assigning this to you, in case you feel like taking a look some time 😄  If not feel free to bounce back!

**Comment by kvz** [comment]
This project has been deprecated. The CLI has been merged into the official `transloadit` npm package.

Please use `npm install transloadit` instead. See the [CLI documentation](https://github.com/transloadit/node-sdk#command-line-interface-cli) for usage.

If this issue is still relevant, please open a new issue at https://github.com/transloadit/node-sdk/issues
